# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cloteaux <- function(a, sorted) {
    .Call(`_StartNetwork_cloteaux`, a, sorted)
}

number_of_graphs_cpp <- function(input, sorted) {
    .Call(`_StartNetwork_number_of_graphs_cpp`, input, sorted)
}

sum_sim <- function(input) {
    .Call(`_StartNetwork_sum_sim`, input)
}

proposal_sim <- function(input) {
    .Call(`_StartNetwork_proposal_sim`, input)
}

ergm_simulator_cpp <- function(init, loops, theta) {
    .Call(`_StartNetwork_ergm_simulator_cpp`, init, loops, theta)
}

graphExists <- function(a) {
    .Call(`_StartNetwork_graphExists`, a)
}

